services:
  updater:
    build:
      context: .
      dockerfile: Dockerfile.updater
    volumes:
      - ./docker-salt-master:/app/docker-salt-master

  salt-master:
    build:
      context: ./docker-salt-master
      dockerfile: Dockerfile
      args:
        - BUILD_DATE=${BUILD_DATE}
        - VCS_REF=${VCS_REF}
    container_name: salt_master
    hostname: salt-master
    environment:
      - SALT_LOG_LEVEL=info
      - SALT_LEVEL_LOGFILE=info
    volumes:
      - ./roots:/home/salt/data/srv
      - ./keys:/home/salt/data/keys
      - ./logs:/home/salt/data/logs
      - ./config:/home/salt/data/config
    ports:
      - "4505:4505"
      - "4506:4506"

  salt-minion:
    build:
      context: .
      dockerfile: Dockerfile.salt-minion
    container_name: salt_minion
    hostname: salt-minion
    volumes:
      - /:/host:ro
    privileged: true
    pid: host
    network_mode: host
    depends_on:
      - salt-master

networks:
  default:
    name: salt-network
